name: ci

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  sgx:
    strategy:
      matrix:
        version: [2.18, 2.19, 2.22]
        distro: [focal]
        dockerfile: [Dockerfile]
        image_name: [sigmagmbh/sgx]
        include:
          - version: 2.18
            distro: jammy
            dockerfile: Dockerfile
            image_name: sigmagmbh/sgx
          - version: 2.19
            distro: jammy
            dockerfile: Dockerfile
            image_name: sigmagmbh/sgx
          - version: 2.19
            distro: bionic
            dockerfile: Dockerfile
            image_name: sigmagmbh/sgx
          - version: 2.19
            distro: focal
            dockerfile: Dockerfile
            image_name: sigmagmbh/sgx
          - version: 2.19
            distro: buster
            dockerfile: Dockerfile
            image_name: sigmagmbh/sgx
          - version: 2.19
            distro: buster
            dockerfile: aesm.Dockerfile
            image_name: sigmagmbh/sgx-aesm
          - version: 2.22
            distro: focal
            dockerfile: Dockerfile
            image_name: sigmagmbh/sgx
          - version: 2.22
            distro: jammy
            dockerfile: Dockerfile
            image_name: sigmagmbh/sgx

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build docker image for SGX SDK & PSW ${{ matrix.version }} ${{ matrix.distro }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./${{ matrix.version }}/${{ matrix.distro }}/${{ matrix.dockerfile }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            sigmagmbh/sgx:${{ matrix.version }}-${{ matrix.distro }},
            sigmagmbh/sgx:${{ matrix.version }}-${{ matrix.distro }}-${{ steps.vars.outputs.short_sha }}
